info:
  contact: {}
paths:
  /get-amount-out:
    get:
      description: Return outputAmount that corresponding uniswap_v2 pool will return
        if you try to swap inputAmount of fromToken in poolID
      parameters:
      - default: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
        description: from token address
        in: query
        name: fromToken
        required: true
        type: string
      - default: "1e18"
        description: amount for swapping
        in: query
        name: inputAmount
        required: true
        type: string
      - default: 0xdac17f958d2ee523a2206206994597c13d831ec7
        description: to token address
        in: query
        name: toToken
        required: true
        type: string
      - default: 0x0d4a11d5eeaac28ec3f61d100daf4d40471f1852
        description: pool address
        in: query
        name: poolID
        required: true
        type: string
      responses:
        "200":
          description: amountOut
          schema:
            type: string
        "400":
          description: error description
          schema:
            type: string
        "500":
          description: error description
          schema:
            type: string
      summary: get amount out
swagger: "2.0"
