info:
  contact: {}
paths:
  /get-amount-out:
    get:
      description: Return outputAmount that corresponding uniswap_v2 pool  will return
        if you try to swap inputAmount of  fromToken
      parameters:
      - description: fromToken
        in: query
        name: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
        required: true
        type: string
      - description: amount for swapping
        in: query
        name: "1000000000000000000"
        required: true
        type: string
      - description: toToken
        in: query
        name: 0xdac17f958d2ee523a2206206994597c13d831ec7
        required: true
        type: string
      - description: poolID
        in: query
        name: 0x0d4a11d5eeaac28ec3f61d100daf4d40471f1852
        required: true
        type: string
      responses:
        "200":
          description: amountOut
          schema:
            type: string
        "404":
          description: error description
          schema:
            type: string
        "500":
          description: error description
          schema:
            type: string
      summary: get amount out
swagger: "2.0"
